---
## file: roles/ansible-sshd/tasks/CentOS_7.yml
#
# Enforcing some settings to harden sshd. While some of the below are
# the defaults, this will ensure that they are so.

- block:
  - name: Including hardening keywords/values
    include_vars:
      file: "vars/_hardened_config.yml"

  - name: Hardening sshd_config
    lineinfile:
      path: "{{ sshd_config_file }}"
      regexp: '^#?\s?{{ item.value.keyword }}'
      line: '{{ item.value.keyword }} {{ item.value.argument }}'
      state: present
      validate: "{{ sshd_binary }} -t -f %s"
    with_dict: "{{ hardened_keywords }}"

  - name: restart sshd
    command: echo "restarting the sshd daemon"
    notify: reload_sshd

  when: sshd_config_hardened
