hardened_keywords:
  challengeresponseauthentication:
    keyword: ChallengeResponseAuthentication
    argument: 'no'
  ignorerhosts:
    keyword: IgnoreRhosts
    argument: 'yes'
  maxauthtries:
    keyword: MaxAuthTries
    argument: '3'
  passwordauthentication:
    keyword: PasswordAuthentication
    argument: 'no'
  permitrootlogin:
    keyword: PermitRootLogin
    argument: 'no'
  protocol:
    keyword: Protocol
    argument: '2'
  pubkeyauthentication:
    keyword: PubkeyAuthentication
    argument: 'yes'
  x11forwarding:
    keyword: X11Forwarding
    argument: 'no'